
- npm init -y
- npm install express puppeteer qrcode

3) วางโค้ด server.js ด้านล่าง แล้วรัน:
- node server.js
- เปิด http://localhost:3000/pdf?id=เลขคำขอ เช่น http://localhost:3000/pdf?id=WP-68-1011897

โค้ดเซิร์ฟเวอร์ (server.js)
```js
const express = require('express');
const path = require('path');
const fs = require('fs/promises');
const QRCode = require('qrcode');
const puppeteer = require('puppeteer');

const app = express();

// เสิร์ฟไฟล์สาธารณะ เช่น bg2.svg
app.use('/static', express.static(path.join(__dirname, 'public')));
